### Import numpy library  

In [1]:
import numpy as np

### Create an Array using array function  

In [2]:
np.array([1,2,3,4,5,6,7,8,9,10])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Create an Array containing numbers from 20 to 40 

In [15]:
np.arange(20,41,1)
np.linspace(20,40,21)

array([20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30., 31., 32.,
       33., 34., 35., 36., 37., 38., 39., 40.])

### Create an array which contain 10 elements and every element is 5  

In [4]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

### create a 1-d array and then convert it into 3-d array  

In [5]:
np.random.randint(1,30,20).reshape(2,5,2)

array([[[22,  3],
        [ 3, 24],
        [ 2, 16],
        [26,  8],
        [22,  8]],

       [[ 1, 10],
        [25, 16],
        [ 3,  3],
        [ 4,  4],
        [27, 25]]])

### Create 2-d array which contains random 25 numbers between 0 and 1 

In [6]:
np.random.rand(5,5)

array([[0.80286937, 0.16777204, 0.47687618, 0.76333421, 0.84419219],
       [0.54446997, 0.61538365, 0.85413139, 0.45309553, 0.08773603],
       [0.39768312, 0.58855709, 0.84719547, 0.86455884, 0.08295663],
       [0.85615581, 0.34195162, 0.13345156, 0.7716805 , 0.7634294 ],
       [0.75850044, 0.3290788 , 0.53737585, 0.81137552, 0.70874113]])

### create array containing 20 random integer then replace every even number with -1 
#### Example - 
####                  array --- >  [44,55,12,6,3] 
####                  ouput ----> [-1,55, -1,-1,3]


In [7]:
arr=np.random.randint(1,20,20)
arr[arr%2==0]=-1
arr

array([-1,  9, -1,  9, -1, -1, -1, 19, 19, 13, 17, -1,  7, 17, 15,  7, 13,
       -1, 13, 17])

#### You have a matrix 
[[5 , 10, 15, 20, 25],
[30, 35, 40, 45, 50],
[55, 60, 65, 70, 75],
[80, 85, 90, 95, 100]]

Extract
[30,35,40]
[55, 60, 65]

In [8]:
arr=np.array([[5 , 10, 15, 20, 25], [30, 35, 40, 45, 50], [55, 60, 65, 70, 75], [80, 85, 90, 95, 100]])
arr[1:3,:3]

array([[30, 35, 40],
       [55, 60, 65]])

### Concatenate two 1-d array   

In [9]:
arr=np.arange(1,10,1)
prr=np.arange(10,20,1)
np.hstack((arr,prr))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

### Stack 2-d matrix horizontally and vertically

In [10]:
arr=np.arange(1,11,1).reshape(5,2)
prr=np.arange(10,20,1).reshape(5,2)
np.hstack((arr,prr))
np.vstack((arr,prr))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])